"""
Universal Attack Stage Taxonomy for SIH26153.
Defines canonical 10-stage attack progression aligned with Cyber Kill Chain
and MITRE ATT&CK enterprise tactics.
"""

from enum import IntEnum
from typing import Dict, List


class AttackStage(IntEnum):
    """Canonical attack stage progression enumeration."""
    UNMAPPED = -1
    NORMAL = 0
    RECONNAISSANCE = 1
    SCANNING = 2
    INITIAL_ACCESS = 3
    EXPLOITATION = 4
    CREDENTIAL_ACCESS = 5
    LATERAL_MOVEMENT = 6
    COMMAND_AND_CONTROL = 7
    EXFILTRATION = 8
    IMPACT_DOS = 9


NUM_ATTACK_STAGES: int = 10

STAGE_NAMES: Dict[int, str] = {
    AttackStage.UNMAPPED: "UNMAPPED",
    AttackStage.NORMAL: "NORMAL",
    AttackStage.RECONNAISSANCE: "RECONNAISSANCE",
    AttackStage.SCANNING: "SCANNING",
    AttackStage.INITIAL_ACCESS: "INITIAL_ACCESS",
    AttackStage.EXPLOITATION: "EXPLOITATION",
    AttackStage.CREDENTIAL_ACCESS: "CREDENTIAL_ACCESS",
    AttackStage.LATERAL_MOVEMENT: "LATERAL_MOVEMENT",
    AttackStage.COMMAND_AND_CONTROL: "COMMAND_AND_CONTROL",
    AttackStage.EXFILTRATION: "EXFILTRATION",
    AttackStage.IMPACT_DOS: "IMPACT_DOS",
}

STAGE_DESCRIPTIONS: Dict[int, str] = {
    AttackStage.UNMAPPED: "Unmapped, ambiguous, or unclassified network telemetry",
    AttackStage.NORMAL: "Benign baseline operational traffic",
    AttackStage.RECONNAISSANCE: "Passive gathering of target intelligence and OSINT",
    AttackStage.SCANNING: "Active port scanning, network sweeps, and vulnerability probing",
    AttackStage.INITIAL_ACCESS: "Perimeter penetration via vulnerable public services or phishing",
    AttackStage.EXPLOITATION: "Execution of exploit code on target software/service",
    AttackStage.CREDENTIAL_ACCESS: "Brute-force, password spraying, or credential harvesting",
    AttackStage.LATERAL_MOVEMENT: "Traversing the internal subnet using pivoting or remote services",
    AttackStage.COMMAND_AND_CONTROL: "Establishing beaconing or reverse shell communication to external C2",
    AttackStage.EXFILTRATION: "Outbound transfer of sensitive compressed/encrypted data",
    AttackStage.IMPACT_DOS: "Disruption, resource exhaustion, or denial-of-service flooding",
}

# Severity weights used for calculating composite risk:
# Risk(t) = sum_c P(Stage = c) * STAGE_SEVERITY_WEIGHTS[c]
STAGE_SEVERITY_WEIGHTS: Dict[int, float] = {
    AttackStage.UNMAPPED: 0.0,
    AttackStage.NORMAL: 0.0,
    AttackStage.RECONNAISSANCE: 1.0,
    AttackStage.SCANNING: 2.0,
    AttackStage.INITIAL_ACCESS: 4.0,
    AttackStage.EXPLOITATION: 6.0,
    AttackStage.CREDENTIAL_ACCESS: 7.0,
    AttackStage.LATERAL_MOVEMENT: 8.0,
    AttackStage.COMMAND_AND_CONTROL: 8.5,
    AttackStage.EXFILTRATION: 10.0,
    AttackStage.IMPACT_DOS: 7.5,
}

# Expected Cyber Kill Chain progression order (for transition penalty & validation)
KILL_CHAIN_ORDER: List[AttackStage] = [
    AttackStage.NORMAL,
    AttackStage.RECONNAISSANCE,
    AttackStage.SCANNING,
    AttackStage.INITIAL_ACCESS,
    AttackStage.EXPLOITATION,
    AttackStage.CREDENTIAL_ACCESS,
    AttackStage.LATERAL_MOVEMENT,
    AttackStage.COMMAND_AND_CONTROL,
    AttackStage.EXFILTRATION,
    AttackStage.IMPACT_DOS,
]


def stage_to_str(stage: AttackStage) -> str:
    """Return string representation of an AttackStage."""
    return STAGE_NAMES.get(int(stage), "UNKNOWN")


def str_to_stage(name: str) -> AttackStage:
    """Parse string representation into an AttackStage."""
    normalized = name.strip().upper().replace(" ", "_").replace("-", "_")
    for stage, stage_name in STAGE_NAMES.items():
        if stage_name == normalized:
            return AttackStage(stage)
    raise ValueError(f"Unknown attack stage name: {name}")


from enum import Enum
from typing import Any


class StateType(str, Enum):
    """Explicit designation for state origin and purpose."""
    OBSERVED = "OBSERVED"                      # Real telemetry observed up to prediction time t
    PREDICTED = "PREDICTED"                    # Forecasted state generated by model for future t+k
    ACTUAL_GROUND_TRUTH = "ACTUAL_GROUND_TRUTH" # Real telemetry observed at future t+k (evaluation only)


# MITRE ATT&CK Enterprise Matrix Mapping for Canonical Attack Stages
STAGE_MITRE_MAPPING: Dict[int, Dict[str, Any]] = {
    AttackStage.UNMAPPED: {
        "tactic_id": "TA0000",
        "tactic_name": "Unmapped",
        "techniques": [],
    },
    AttackStage.NORMAL: {
        "tactic_id": "TA0000",
        "tactic_name": "Benign Operational",
        "techniques": [],
    },
    AttackStage.RECONNAISSANCE: {
        "tactic_id": "TA0043",
        "tactic_name": "Reconnaissance",
        "techniques": ["T1595 (Active Scanning)", "T1592 (Gather Victim Host Info)"],
    },
    AttackStage.SCANNING: {
        "tactic_id": "TA0043",
        "tactic_name": "Reconnaissance: Network & Port Probing",
        "techniques": ["T1595.001 (Port Scanning)", "T1595.002 (Vulnerability Scanning)"],
    },
    AttackStage.INITIAL_ACCESS: {
        "tactic_id": "TA0001",
        "tactic_name": "Initial Access",
        "techniques": ["T1190 (Exploit Public-Facing Application)", "T1566 (Phishing)"],
    },
    AttackStage.EXPLOITATION: {
        "tactic_id": "TA0002",
        "tactic_name": "Execution",
        "techniques": ["T1203 (Exploitation for Client Execution)", "T1059 (Command & Scripting Interpreter)"],
    },
    AttackStage.CREDENTIAL_ACCESS: {
        "tactic_id": "TA0006",
        "tactic_name": "Credential Access",
        "techniques": ["T1110 (Brute Force)", "T1003 (OS Credential Dumping)"],
    },
    AttackStage.LATERAL_MOVEMENT: {
        "tactic_id": "TA0008",
        "tactic_name": "Lateral Movement",
        "techniques": ["T1021 (Remote Services: SSH/RDP/SMB)", "T1080 (Taint Shared Content)"],
    },
    AttackStage.COMMAND_AND_CONTROL: {
        "tactic_id": "TA0011",
        "tactic_name": "Command and Control",
        "techniques": ["T1071 (Application Layer Protocol: HTTP/DNS)", "T1095 (Non-Application Layer Protocol)", "T1573 (Encrypted Channel)"],
    },
    AttackStage.EXFILTRATION: {
        "tactic_id": "TA0010",
        "tactic_name": "Exfiltration",
        "techniques": ["T1048 (Exfiltration Over Alternative Protocol)", "T1041 (Exfiltration Over C2 Channel)", "T1567 (Exfiltration to Cloud Storage)"],
    },
    AttackStage.IMPACT_DOS: {
        "tactic_id": "TA0040",
        "tactic_name": "Impact",
        "techniques": ["T1498 (Network Denial of Service)", "T1499 (Endpoint Denial of Service)"],
    },
}

